export interface IThemeColors {
  white: string;
  white2: string;
  light: string;
  grayLight: string;
  gray: string;
  gray2: string;
  gray3: string;
  gray4: string;
  gray5: string;
  gray6: string;
  gray7: string;
  gray9: string;
  gray10: string;
  gray11: string;
  dark: string;
  black: string;
  blue: string;
  darkBlue: string;
  darkBlue2: string;
  borderLight: string;
  grayHover: string;
  red: string;
  red2: string;
  red3: string;
  purple: string;
  orange: string;
  blueLight: string;
  rose: string;
  green: string;
  green1: string;
  green2: string;
  green3: string;
  green4: string;
  greenLight: string;
  turquoise: string;
  submarine: string;
  elephant: string;
  feijoa: string;
  slate: string;
  asparagus: string;
  persimmon: string;
  malibu: string;
  navy: string;
  alto: string;
}

export const colorPalette: IThemeColors = {
  white: '#ffffff',
  white2: '#dddddd',
  light: '#d5dae0',
  grayLight: '#cdd0d5',
  gray: '#a5adb8',
  gray2: '#a7a9ac',
  gray3: '#a1aab6',
  gray4: '#e8e8e8',
  gray5: '#cbcbcb',
  gray6: '#eaeaea',
  gray7: '#acacac',
  gray9: '#9faab7',
  gray10: '#cad3db',
  gray11: '#959fac',
  dark: '#030303',
  black: '#000000',
  blue: '#008cff',
  darkBlue: '#011f3d',
  darkBlue2: '#132F4B',
  borderLight: '#cad3db',
  grayHover: '#00000008',
  red: '#e10606',
  red2: '#ff2e7b',
  red3: '#ea4848',
  purple: '#a479cb',
  orange: '#e4be79',
  blueLight: '#70cde4',
  rose: '#d08484',
  green: '#7ed321',
  green1: '#5ba00f',
  green2: '#4dd964',
  green3: '#77a45c',
  green4: '#b1de6b',
  greenLight: '#d9f9b6',
  turquoise: '#79cbcb',
  submarine: '#b6bcc4',
  elephant: '#12304b',
  feijoa: '#93d77e',
  slate: '#596778',
  asparagus: '#77a45c',
  persimmon: '#ff5353',
  malibu: '#53b8ff',
  navy: '#01172d',
  alto: '#dedede',
};
